name: Manual Approval Workflow

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  request-approval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Manual Approval
        uses: trstringer/manual-approval@main
        with:
          approvers: "user1,user2" # Replace with approver usernames
          title: "Deploy to Production"
          body: "Please review and approve the deployment to production."
          approved-keyword: "approve"
          denied-keyword: "deny"

  after-approval:
    needs: request-approval
    runs-on: ubuntu-latest
    environment:
      name: production # Requires approval from environment reviewers
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
