name: Deployment with Manual Input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the deployment environment"
        required: true
        default: "production"
        type: choice
        options:
          - staging
          - production
      deploy_version:
        description: "Enter the deployment version (e.g., v1.2.3)"
        required: true
      confirmation:
        description: "Type 'CONFIRM' to proceed"
        required: true

jobs:
  approval:
    name: Await Manual Input
    runs-on: ubuntu-latest
    steps:
      - name: Validate User Input
        run: |
          if [[ "${{ github.event.inputs.confirmation }}" != "CONFIRM" ]]; then
            echo "Deployment not confirmed. Exiting..."
            exit 1
          fi
          echo "User confirmed deployment to ${{ github.event.inputs.environment }} with version ${{ github.event.inputs.deploy_version }}"

  deploy:
    name: Deploy to Selected Environment
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          echo "Deploying version ${{ github.event.inputs.deploy_version }} to ${{ github.event.inputs.environment }}..."
          # Add deployment commands here
