name: Deployment with Approval

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  approval:
    name: Await Approval
    runs-on: ubuntu-latest
    environment: production  # Requires manual approval if enabled in environment settings
    steps:
      - name: Request Approval
        run: echo "Waiting for manual approval..."

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: approval  # Waits for approval job to complete
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          echo "Deploying to production..."
          # Add deployment commands here

  after-approval:
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: production # Requires approval from environment reviewers
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
