name: Manual Approval Workflow

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  request-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval
        run: echo "Please approve this workflow run."

  after-approval:
    needs: request-approval
    runs-on: ubuntu-latest
    environment:
      name: production # Requires approval from environment reviewers
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
